### ISSUE TITLE
Extra interface functions

### ISSUE THREAD

**Issue by vrom911** [kowainik/validation-selective#24]
* `whenSuccess`
* `whenFailure`
* `whenSuccess_`
* `whenFailure_`
* `whenSuccessM`
* `whenFailureM`

**Comment by chshersh** [comment]
@vrom911 Good idea! I guess we can even put them in some module like `Validation.Combinators`

**Comment by chshersh** [comment]
One more useful function to add: run multiple validations on a single value. Something like:

```haskell
validateAll :: Semigroup e => [a -> Validation e b] -> a -> Validation e a
```

Can be used like:

```haskell
validatePassword = validateAll
    [ validateEmptyPassword
    , validateShortPassword
    ]
```
