### ISSUE TITLE
What to do when I need a Monad

### ISSUE THREAD

**Issue by anka-213** [kowainik/validation-selective#59]
My case is this:

I want to type check a recursive expression and the type checking may depend on the type of the  child expressions. I want to collect all the errors from all the children, but if one of my children has an error, there is no need to report another error for this node as well.

Basically I want the `Either` monad instance for the specific case, but the applicative of `Validation` for everything else. Or not even that. If this had the Either monad instance (which obviously won't happen), I would still have to write:

```haskell
tpCheck :: Exp () -> Validation (Exp Tp)
tpCheck (BinaryExp op a b ()) = do
  (ta, tb) <- (,) <$> tpCheck a <*> tpCheck b
  BinaryExp op ta tb <$> tpCheckBinary op ta tb
  
 tpCheckBinary :: Op -> Exp Tp -> Exp Tp -> Validation Tp
```
which feels kind of indirect and silly, with the `(,) <$>` part. I wonder if there is some kind of operator that would allow me to do the whole thing more directly:
```haskell
tpCheck (BinaryExp op a b ()) = do
  tpCheckBinary op <$!?> tpCheck a <*> tpCheck b
  
tpCheckBinary :: Op -> Exp Tp -> Exp Tp -> Validation (Exp Tp)
```

From my understanding, selective is more restrictive and wouldn't allow expressing this, since it really wants to collect errors from everything?

Maybe the answer is to just use another `Validation` library with a non-law abiding instance and accept the slight ugliness and the need to be careful? Or to manually convert it back and forth to `Either`?

**Comment by vrom911** [comment]
This is out of the scope of this library. By design `Validation` can't have a Monad instance as it breaks the laws.

**Comment by anka-213** [comment]
Yeah, I expected as much. I think my main question is if there is some other abstraction on top of this library that would allow me to do what I need? I fully agree that this library shouldn’t be an instance of Monad.
