### ISSUE TITLE
Add to stack

### ISSUE THREAD

**Issue by flip111** [kowainik/validation-selective#75]
Could the library be re-added to stack ?

At the moment it's listed as unmaintained https://github.com/commercialhaskell/stackage/issues/6486#issuecomment-1073120841 i guess it's meant unmaintained from that point onward

**Comment by vrom911** [comment]
Hi @flip111 ,

The library is available on Hackage, which is enough to use it with both Cabal and Stack build tools.
The Stack support brings additional burden of maintenance, for which, unfortunately, I do not have enough time right now.

Note, that you can use `extra-deps` in your `stack.yaml` if you want a specific version of `validation-selective` be used in your project, so there should be no problems with using the library with Stack.
