### ISSUE TITLE
Add more interface functions

### ISSUE THREAD

**Issue by chshersh** [kowainik/validation-selective#8]
We can add more interface functions, similar to `Either`:

* http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Either.html

Specifically:

* `isFailure`
* `isSuccess`
* `validation` eliminator (similar to `either` function)
* `failures`
* `successes`
* `partitionValidations`
* `fromFailure`
* `fromSuccess`

Any other ideas?

**Comment by vrom911** [comment]
what do you think about such type of functions?
* `whenSuccess`
* `whenFailure`
* `whenSuccess_`
* `whenFailure_`
* `whenSuccessM`
* `whenFailureM`

**Comment by vrom911** [comment]
@chshersh thinking more about these function I proposed, I think we can create a separate issue for that as they are not essential for the interface.
