### ISSUE TITLE
Add to stackage?

### ISSUE THREAD

**Issue by telser** [kowainik/validation-selective#88]
Would the maintainers here be open to adding this library to stackage?

**Comment by tomjaguarpaw** [comment]
I'm happy for it to be included in Stackage but I don't have the bandwidth to take responsibility for that. @Kleidukos?

**Comment by Kleidukos** [comment]
Quite unfortunately I'm in the same situation.

**Comment by tomjaguarpaw** [comment]
If a third party wants to add it, I think we're fine with that.

**Comment by telser** [comment]
I'm happy to add it under my name there, but did not want to do so without at least asking here first. Thank you both for being so quick to respond!

**Comment by tomjaguarpaw** [comment]
You're welcome, and thanks for your contribution!

**Comment by telser** [comment]
@tomjaguarpaw I think the only thing preventing the addition will be a revision on hackage with the test suite bounds relaxed as you did in 8cd8c80507c8e18459bc997ad6063b615eaf7c05. Specifically, the bounds on `hspec-hedgehog` and `text`. 

If we can get a revision with those relaxations I'll open the stackage pr and close this issue.

**Comment by tomjaguarpaw** [comment]
OK, done here: https://hackage.haskell.org/package/validation-selective-0.2.0.0/revisions/
